#' @useDynLib BANDITS, .registration=TRUE
#' @importFrom MASS ginv
#' @importFrom doRNG '%dorng%'
#' @importFrom data.table fread
#' @importFrom data.table last
#' @importFrom parallel parLapply
#' @importFrom parallel makeCluster
#' @importFrom parallel stopCluster
#' @importFrom doParallel registerDoParallel
#' @importFrom doParallel stopImplicitCluster
#' @importFrom foreach foreach
#' @importFrom foreach '%dopar%'
#' @importFrom DRIMSeq dmDSdata
#' @importFrom DRIMSeq dmFilter
#' @importFrom DRIMSeq dmPrecision
#' @importFrom DRIMSeq samples
#' @importFrom DRIMSeq genewise_precision
#' @importFrom Rcpp evalCpp
#' @importFrom BiocParallel MulticoreParam
#' @importFrom methods is
#' @importFrom methods new
#' @importFrom methods show
#' @importFrom ggplot2 aes_string
#' @importFrom ggplot2 geom_bar
#' @importFrom ggplot2 ggplot
#' @importFrom ggplot2 position_dodge
#' @importFrom ggplot2 theme_bw
#' @importFrom ggplot2 theme
#' @importFrom ggplot2 element_text
#' @importFrom ggplot2 ggtitle
#' @importFrom ggplot2 xlab
#' @importFrom ggplot2 ylab
#' @importFrom ggplot2 geom_point
#' @importFrom ggplot2 geom_errorbar
#' @importFrom graphics curve
#' @importFrom graphics hist
#' @importFrom stats ar
#' @importFrom stats cov
#' @importFrom stats density
#' @importFrom stats dnorm
#' @importFrom stats lm
#' @importFrom stats median
#' @importFrom stats model.matrix
#' @importFrom stats p.adjust
#' @importFrom stats pchisq
#' @importFrom stats residuals
#' @importFrom stats window
#' @importFrom stats qnorm
#' @importFrom stats sd
#' @importFrom stats var
NULL